name = "ubicaciones-cr"
main = ".worker-next/index.mjs"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
minify = true
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
